import streamlit as st
import sys
import threading
import queue
import time
import warnings
from pathlib import Path

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

# ── Fix import path ───────────────────────────────────────────────────────────
_root = Path(__file__).resolve().parent
_src  = _root / "src"
for _p in [str(_root), str(_src)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ── Default topic & hardcoded report ─────────────────────────────────────────
DEFAULT_TOPIC = "Impact of AI"

DEFAULT_REPORT = """# Level Up Your Life: How AI is Secretly Rocking Your World! 🚀🎮

Hey future leaders, digital natives, and tech wizards! 👋 Ever wonder who's really making your games more epic, helping your phone understand your voice, or suggesting the next binge-worthy show? 🤔 Chances are, it's AI – Artificial Intelligence! It sounds super sci-fi, but trust me, AI is already a massive part of your everyday life, and it's only getting cooler! ✨

## What Even IS AI? Think Super Student! 🤓

So, what exactly is AI? Imagine a super-smart student 🤓 who can read every book in the library in seconds, remember everything perfectly, and then connect all the dots to solve any puzzle. That's a bit like AI! It's a computer program that can learn, understand, and even make decisions, almost like a human brain, but way faster! 💨

Think of it like giving a robot a super detailed recipe. 🧑‍🍳 If you give it instructions, AI can follow them perfectly to bake a cake. The more recipes (or data) it gets, the better it becomes at baking (or doing its task)!

## AI All Around You: Everyday Superpowers! 🕵️‍♀️

You might not even realize it, but AI is already your invisible sidekick in tons of cool ways:

- **Your Personal Assistant 🗣️🎤**: Ever asked Siri or Alexa for the weather or to play your favorite song? That's AI! It understands your voice and zips to find the info.
- **The Tidy-Up Trooper 🧹**: Those little robotic vacuums (like Roomba) zooming around your house? They use AI to map your rooms and dodge your scattered toys.
- **Your Entertainment Guru 🎬🎶**: When Netflix suggests your next show, or YouTube knows which video you'll love, that's AI at work!
- **Digital Dress-Up Magic 🤳🐶**: Those hilarious face filters on Snapchat or Instagram? AI helps them recognize your face and perfectly place those dog ears or funky glasses.
- **Your Email's Guard Dog 📧🚫**: Those annoying junk emails that never reach your inbox? Thank AI! It learns to spot suspicious messages.

## Mind-Blowing AI Facts You Need To Know! 🤩

- **Speed Demon Reader! 📖💨** AI can read and understand a whole book much, much faster than any human can.
- **Gaming Level Up! 🎮** Many of your favorite video games use AI to make characters smarter and more challenging.
- **AI Can Be an Artist! 🎨🎵** There are AIs that can draw incredible pictures, compose catchy music, and even write exciting stories!
- **Doctor's Super Helper! 👩‍⚕️** AI helps doctors spot tiny problems in X-rays or scans that humans might miss.
- **Always Learning! 🧠** Just like you learn new things at school every day, AI programs are constantly being taught new information and skills.
- **Chatting with AI is Normal! 💬** Recent research shows that over 73% of teenagers (ages 13-18) have talked to an AI chatbot at least once!

## The Future with AI: Your Ultimate Sidekick! 🚀

AI isn't just cool now; it's shaping our future too! Imagine cars that can drive themselves 🚗💨, or AI helping you learn new subjects in school by acting like a robot librarian 📚. AI can be a super detective 🕵️‍♀️, sifting through massive amounts of data to find clues and solve big problems.

## So, What's Next? Get Ready! ✨

AI is like a powerful tool that humans create and teach. It's here to help us, make our lives easier, and even spark our creativity. As you grow up, AI will be an even bigger part of your world, opening up new jobs and exciting possibilities we can't even imagine yet!

So, next time you interact with a smart device or get a perfect recommendation, give a little nod to AI. It's your brainy buddy, making the world a more amazing place, one smart decision at a time! 👍

---
*Generated by CrewAI Blog Generation Crew*
"""

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(page_title="CrewAI Console", page_icon="🤖", layout="wide")

# ── CSS ───────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Space+Grotesk:wght@400;600&display=swap');

html, body, [class*="css"] { font-family: 'Space Grotesk', sans-serif; background: #0a0c0f; color: #e0e6ef; }
#MainMenu, footer, header { visibility: hidden; }
.stApp { background: #0a0c0f; }

[data-testid="stSidebar"] { background: #111418 !important; border-right: 1px solid #1e242c; }
[data-testid="stSidebar"] * { color: #e0e6ef !important; }

.stTextArea textarea {
    background: #181c22 !important; border: 1px solid #1e242c !important;
    color: #e0e6ef !important; font-family: 'JetBrains Mono', monospace !important;
    font-size: 13px !important; border-radius: 6px !important;
}
.stTextArea textarea:focus { border-color: #00e676 !important; box-shadow: 0 0 0 1px #00e676 !important; }

.stButton > button {
    background: #00e676 !important; color: #000 !important; font-weight: 600 !important;
    border: none !important; border-radius: 7px !important; width: 100% !important;
    padding: 10px !important; font-size: 14px !important;
}
.stButton > button:hover { background: #00ff8a !important; }
.stButton > button:disabled { opacity: 0.4 !important; }

[data-testid="stDownloadButton"] button {
    background: #00b4d8 !important; color: #000 !important; font-weight: 600 !important;
    border: none !important; border-radius: 7px !important; width: 100% !important;
    padding: 10px !important; font-size: 14px !important;
}

.terminal {
    background: #0a0c0f; border: 1px solid #1e242c; border-radius: 10px;
    overflow: hidden; height: 520px; display: flex; flex-direction: column;
}
.terminal-bar {
    background: #181c22; padding: 8px 14px; border-bottom: 1px solid #1e242c;
    display: flex; align-items: center; gap: 6px; flex-shrink: 0;
}
.dot { display:inline-block; width:11px; height:11px; border-radius:50%; }
.dr{background:#ff5f57;}.dy{background:#febc2e;}.dg{background:#28c840;}
.terminal-title { font-family:'JetBrains Mono',monospace; font-size:11px; color:#5a6478; margin-left:4px; }
.terminal-body {
    flex: 1; overflow-y: auto; padding: 14px 18px;
    font-family: 'JetBrains Mono', monospace; font-size: 12px; line-height: 1.75;
}
.terminal-body::-webkit-scrollbar { width: 4px; }
.terminal-body::-webkit-scrollbar-thumb { background: #1e242c; border-radius: 4px; }

.badge { display:inline-block; padding:3px 10px; border-radius:20px; font-family:'JetBrains Mono',monospace; font-size:11px; letter-spacing:1px; }
.idle    { background:#181c22; border:1px solid #1e242c; color:#5a6478; }
.running { background:#00e67612; border:1px solid #00e676; color:#00e676; }

.demo-tag { display:inline-block; padding:2px 8px; border-radius:4px; background:#ff980015; border:1px solid #ff9800; color:#ff9800; font-family:'JetBrains Mono',monospace; font-size:10px; margin-top:6px; }
</style>
""", unsafe_allow_html=True)


# ── Session state ─────────────────────────────────────────────────────────────
for k, v in [("logs", []), ("running", False), ("report", None), ("q", None)]:
    if k not in st.session_state:
        st.session_state[k] = v


# ── Stdout → Queue ────────────────────────────────────────────────────────────
class Tee:
    def __init__(self, q, original):
        self.q, self.original, self._buf = q, original, ""

    def write(self, text):
        self.original.write(text)
        self._buf += text
        while "\n" in self._buf:
            line, self._buf = self._buf.split("\n", 1)
            if line.strip():
                self.q.put(("log", line))

    def flush(self): self.original.flush()
    def isatty(self): return False


# ── Background crew worker (real CrewAI call) ─────────────────────────────────
def crew_worker(topic: str, q: queue.Queue):
    import signal as _signal
    _orig_signal = _signal.signal
    def _safe_signal(sig, handler):
        try:
            return _orig_signal(sig, handler)
        except (ValueError, OSError):
            pass
    _signal.signal = _safe_signal

    orig_out, orig_err = sys.stdout, sys.stderr
    sys.stdout = Tee(q, orig_out)
    sys.stderr = Tee(q, orig_err)
    try:
        from dotenv import load_dotenv
        load_dotenv(dotenv_path=str(_root / ".env"), override=False)

        from blow_generation_crew.crew import BlowGenerationCrew
        BlowGenerationCrew().crew().kickoff(inputs={"topic": topic})
        q.put(("done", None))
    except Exception as e:
        q.put(("log", f"[ERROR] {e}"))
        q.put(("done", None))
    finally:
        _signal.signal = _orig_signal
        sys.stdout = orig_out
        sys.stderr = orig_err


# ── Line coloriser ────────────────────────────────────────────────────────────
def colorise(line: str) -> str:
    low = line.lower()
    if "error" in low or "exception" in low:
        color = "#ff5555"
    elif "tool" in low:
        color = "#ff9800"
    elif any(k in low for k in ("task output", "final answer", "completed", "✓", "finished")):
        color = "#00e676"
    elif any(k in low for k in ("working agent", "agent:", "thought:", "action:")):
        color = "#00b4d8"
    else:
        color = "#8899aa"
    safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return f'<div style="color:{color}">{safe}</div>'


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🤖 CrewAI Console")
    st.divider()

    topic = st.text_area(
        "Blog Topic",
        value=DEFAULT_TOPIC,
        height=120,
    )

    is_default = topic.strip().lower() == DEFAULT_TOPIC.lower()
    if is_default:
        st.markdown('<span class="demo-tag">⚡ DEMO — using sample report</span>', unsafe_allow_html=True)
    else:
        st.markdown(
            '<p style="color:#00e676;font-family:JetBrains Mono,monospace;font-size:10px;margin-top:4px">✓ Will run real CrewAI crew</p>',
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)
    run_btn = st.button("▶  Run Crew", disabled=st.session_state.running)

    if st.session_state.report:
        st.markdown("<br>", unsafe_allow_html=True)
        st.download_button(
            "⬇  Download report.md",
            data=st.session_state.report,
            file_name="report.md",
            mime="text/markdown",
        )


# ── Main area ─────────────────────────────────────────────────────────────────
h1, h2 = st.columns([5, 1])
with h1:
    st.markdown("## CrewAI Live Console")
with h2:
    badge = "running" if st.session_state.running else "idle"
    label = "● RUNNING" if st.session_state.running else "● IDLE"
    st.markdown(
        f'<div style="margin-top:20px;text-align:right"><span class="badge {badge}">{label}</span></div>',
        unsafe_allow_html=True,
    )

st.divider()

# ── Terminal ──────────────────────────────────────────────────────────────────
body_html = "\n".join(colorise(l) for l in st.session_state.logs) or \
    '<span style="color:#5a6478">Waiting for crew to start…</span>'

st.markdown(f"""
<div class="terminal">
  <div class="terminal-bar">
    <span class="dot dr"></span><span class="dot dy"></span><span class="dot dg"></span>
    <span class="terminal-title">crew_output — bash</span>
  </div>
  <div class="terminal-body" id="tb">{body_html}</div>
</div>
<script>
  var tb = document.getElementById('tb');
  if (tb) tb.scrollTop = tb.scrollHeight;
</script>
""", unsafe_allow_html=True)

# ── Report preview ────────────────────────────────────────────────────────────
if st.session_state.report:
    st.divider()
    with st.expander("📄 Report Preview", expanded=True):
        st.markdown(st.session_state.report)


# ── Launch: default topic → instant hardcoded report, custom → real crew ─────
if run_btn and topic.strip() and not st.session_state.running:
    st.session_state.logs   = []
    st.session_state.report = None

    if is_default:
        # Show demo log lines then load the hardcoded report instantly
        st.session_state.logs = [
            f"[demo] Topic: \"{topic.strip()}\"",
            "[demo] Loading sample report (no API call made)…",
            "[demo] Report ready ✓  — change the topic to run the real crew",
        ]
        st.session_state.report = DEFAULT_REPORT
        st.rerun()
    else:
        # Real crew call in background thread
        st.session_state.running = True
        q = queue.Queue()
        st.session_state.q = q
        threading.Thread(target=crew_worker, args=(topic.strip(), q), daemon=True).start()
        st.rerun()


# ── Poll queue while real crew runs ──────────────────────────────────────────
if st.session_state.running and st.session_state.q:
    q = st.session_state.q
    done = False

    while not q.empty():
        try:
            kind, val = q.get_nowait()
            if kind == "log":
                st.session_state.logs.append(val)
            elif kind == "done":
                done = True
        except queue.Empty:
            break

    if done:
        st.session_state.running = False
        st.session_state.q = None
        p = Path("report.md")
        if p.exists():
            st.session_state.report = p.read_text(encoding="utf-8")
        st.rerun()
    else:
        time.sleep(1)
        st.rerun()